server:
  port: 8130
spring:
  profiles:
    active: dev
  application:
    name: service-oss
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848  # nacos服务地址
aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com
    keyId: your key
    keySecret: your key password
    bucketName: zhouhui-srb